# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/fb17fdc1-9922-4601-b3ff-63ddd57e2f1a";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EBB8-CFC0";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-17dac40b2151.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-20ebdd9973da.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-2456ae9e72bb.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-2d1b7dbb4543.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-2f21b6ec71cd.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-320dbc0ef55f.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-3d04a7accfdb.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-496aed6c39af.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-49e5a7ed4af8.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-53b6903c0101.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-6d155d45110e.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-857af694e099.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-a1226c16f36d.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-a9015b700725.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-b211a3301676.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-be0d6f6b9aed.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-c3d641cba140.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-d2ffdc172f58.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-d8c5d6cc0963.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-dc68626feb3a.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-ec420b55e920.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-ede9533bf9b6.useDHCP = lib.mkDefault true;
  # networking.interfaces.br0.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp8s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth01fa18c.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth03ca21f.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth12eb22a.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth17bf983.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth1f0e599.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth2053a88.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth3336ed8.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth4158971.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth4ebd945.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth501073f.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth5267336.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth5899085.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth613413c.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth701db24.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth8bfa392.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth8ef6d51.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth9e02d92.useDHCP = lib.mkDefault true;
  # networking.interfaces.vetha074724.useDHCP = lib.mkDefault true;
  # networking.interfaces.vetha57b064.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethb654ee6.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethb9a7a5b.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethc335b02.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethc71c82f.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethcfe8db0.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethef96c9d.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethf8cd75b.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethfefae8f.useDHCP = lib.mkDefault true;
  # networking.interfaces.virbr0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
