global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v2

scrape_configs:
- job_name: node
  static_configs:
  - targets: ['host.docker.internal:9100']
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: 'minecraft'
  static_configs:
    - targets: ['minecraft_dev:9940']
      labels:
        server_name: 'minecraft-dev'
    - targets: ['hserver:9940']
      labels:
        server_name: 'hserver'

rule_files:
  - "node_rules.yaml"
