{
 "title": "Modded Potato SMP Stats",
 "description": "Displays server stats exported by https://github.com/cpburnz/minecraft-prometheus-exporter",
 "tags": [
  "JVM",
  "minecraft"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "application",
    "query": {
     "query": "label_values(mc_dimension_chunks_loaded, application)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(mc_dimension_chunks_loaded{application=\"$application\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{application=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{application=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 16, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(jvm_info{application=\"$application\", instance=\"$instance\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
    }
   ]
  },
  { "title": "Minecraft Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Players Online",
   "type": "state-timeline",
   "gridPos": { "h": 16, "w": 5, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "mc_player_list{application=\"$application\", instance=\"$instance\", name!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "# Chunks Loaded",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 5, "x": 5, "y": 6 },
   "targets": [
    {
     "expr": "mc_dimension_chunks_loaded{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Server Tick Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mc_server_tick_seconds_bucket{application=\"$application\", instance=\"$instance\"}[5m])) by (le))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "95th Percentile Tick Time by World",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mc_dimension_tick_seconds_bucket[5m])) by (name, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Tick Rate",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 14 },
   "targets": [
    {
     "expr": "clamp_max(rate(mc_server_tick_seconds_count{application=\"$application\", instance=\"$instance\"}[5m]), 20)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Tick Rate By World",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "tps" } },
   "targets": [
    {
     "expr": "clamp_max(sum(rate(mc_dimension_tick_seconds_count[5m])) by (name), 20)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 23 },
   "repeat": "memarea",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{application=\"$application\", instance=\"$instance\", area=\"heap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": " jvm_memory_bytes_max{application=\"$application\", instance=\"$instance\", area=\"heap\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_bytes_committed{application=\"$application\", instance=\"$instance\", area=\"heap\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Non-Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{application=\"$application\", instance=\"$instance\", area=\"nonheap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": " jvm_memory_bytes_max{application=\"$application\", instance=\"$instance\", area=\"nonheap\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_bytes_committed{application=\"$application\", instance=\"$instance\", area=\"nonheap\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Mem Pool: PS Eden",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{application=\"$application\", instance=\"$instance\",pool=\"PS Eden Space\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{application=\"$application\", instance=\"$instance\",pool=\"PS Eden Space\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{application=\"$application\", instance=\"$instance\",pool=\"PS Eden Space\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Mem Pool: Metaspace",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{application=\"$application\", instance=\"$instance\",pool=\"Metaspace\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{application=\"$application\", instance=\"$instance\",pool=\"Metaspace\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{application=\"$application\", instance=\"$instance\",pool=\"Metaspace\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Mem Pool: Code Cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{application=\"$application\", instance=\"$instance\",pool=\"Code Cache\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{application=\"$application\", instance=\"$instance\",pool=\"Code Cache\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{application=\"$application\", instance=\"$instance\",pool=\"Code Cache\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Mem Pool: Compressed Class Space",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
   "repeat": "mempool",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{application=\"$application\", instance=\"$instance\",pool=\"Compressed Class Space\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{application=\"$application\", instance=\"$instance\",pool=\"Compressed Class Space\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{application=\"$application\", instance=\"$instance\",pool=\"Compressed Class Space\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 4, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "jvm_threads_current{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "JVM current threads"
    },
    {
     "expr": "jvm_threads_daemon{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "JVM daemon threads"
    },
    {
     "expr": "jvm_threads_deadlocked{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "JVM deadlocked threads"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 4, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{application=\"$application\", instance=\"$instance\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Mem Pool: PS Survivor",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{application=\"$application\", instance=\"$instance\",pool=\"PS Survivor Space\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{application=\"$application\", instance=\"$instance\",pool=\"PS Survivor Space\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{application=\"$application\", instance=\"$instance\",pool=\"PS Survivor Space\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Mem Pool: PS Old",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{application=\"$application\", instance=\"$instance\",pool=\"PS Old Gen\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{application=\"$application\", instance=\"$instance\",pool=\"PS Old Gen\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{application=\"$application\", instance=\"$instance\",pool=\"PS Old Gen\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "JVM Classes Loaded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 59 },
   "targets": [
    {
     "expr": "jvm_classes_currently_loaded{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC count increase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 4, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{application=\"$application\", instance=\"$instance\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "JVM Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 67 },
   "targets": [
    {
     "expr": "process_open_fds{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "{{gc}}"
    }
   ]
  }
 ]
}